apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: runtime-detect
  name: runtime-detect
  namespace: default
spec:
  selector:
    matchLabels:
      app: runtime-detect
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: runtime-detect
    spec:
      containers:
      - image: dev/runtime-detector:test
      #- image: public.ecr.aws/y2v0v6s7/dev/runtime-detector:test
      # imagePullPolicy: Always
        name: runtime-detector
        resources: {}
        securityContext:
          capabilities:
            add:
            - BPF        # needed to load eBPF programs and maps
            - PERFMON    # needed to load tracepoints eBPF programs
            - SYS_PTRACE # needed to read /proc files
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /sys/kernel/debug
          name: kernel-debug
      dnsPolicy: ClusterFirst
      hostPID: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: kernel-debug
        hostPath:
          path: /sys/kernel/debug
          type: ""
