apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: runtime-detect
  name: runtime-detect
  namespace: default
spec:
  selector:
    matchLabels:
      app: runtime-detect
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: runtime-detect
    spec:
      containers:
      - image: dev/runtime-detector:test
        imagePullPolicy: IfNotPresent
        name: runtime-detector
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /sys/kernel/debug
          name: kernel-debug
        - mountPath: /procHost
          name: host-proc
        env:
        # when deploying in a kind cluster, the /proc filesystem is not the same as the host's
        # this environment variable is used to tell the runtime-detector container where to find the host's /proc filesystem
        - name: PROC_FS_PATH
          value: "/procHost"
      dnsPolicy: ClusterFirst
      hostPID: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: kernel-debug
        hostPath:
          path: /sys/kernel/debug
          type: ""
      - name: host-proc
        hostPath:
          path: /procHost
          type: Directory
