apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: runtime-detect
  name: runtime-detect
  namespace: default
spec:
  selector:
    matchLabels:
      app: runtime-detect
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: runtime-detect
    spec:
      containers:
      - image: dev/runtime-detector:test
      #- image: public.ecr.aws/y2v0v6s7/dev/runtime-detector:test
      # imagePullPolicy: Always
        name: runtime-detector
        resources: {}
        env:
        - name: HOST_PROCFS
          value: /hostproc
        securityContext:
          privileged: false
          capabilities:
            add:
            - BPF
            - PERFMON
            - SYS_PTRACE
            - DAC_READ_SEARCH
            drop:
            - ALL
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /sys/kernel/debug
          name: kernel-debug
        - mountPath: /hostproc
          name: host-proc
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: kernel-debug
        hostPath:
          path: /sys/kernel/debug
          type: ""
      - name: host-proc
        hostPath:
          path: /proc
          type: Directory