apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: runtime-detect
  name: runtime-detect
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: runtime-detect
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: runtime-detect
    spec:
      containers:
      - image: dev/runtime-detector:test
        imagePullPolicy: IfNotPresent
        name: runtime-detector
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /sys/kernel/debug
          name: kernel-debug
      dnsPolicy: ClusterFirst
      hostPID: true
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /sys/kernel/debug
          type: ""
        name: kernel-debug