// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package probe

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpf_smallDetectorConfigT struct {
	_                    structs.HostLayout
	ConfiguredPidNsInode uint32
	Padding              [4]uint8
	NumOpenPathsToTrack  uint8
	NumExecPathsToFilter uint8
	Padding2             [6]uint8
}

type bpf_smallEnvPrefixT struct {
	_      structs.HostLayout
	Len    uint64
	Prefix [16]uint8
}

type bpf_smallExecFilenameT struct {
	_   structs.HostLayout
	Len uint64
	Buf [64]uint8
}

type bpf_smallOpenFilenameT struct {
	_   structs.HostLayout
	Len uint64
	Buf [128]uint8
}

// loadBpf_small returns the embedded CollectionSpec for bpf_small.
func loadBpf_small() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Bpf_smallBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf_small: %w", err)
	}

	return spec, err
}

// loadBpf_smallObjects loads bpf_small and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpf_smallObjects
//	*bpf_smallPrograms
//	*bpf_smallMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpf_smallObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf_small()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpf_smallSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_smallSpecs struct {
	bpf_smallProgramSpecs
	bpf_smallMapSpecs
	bpf_smallVariableSpecs
}

// bpf_smallProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_smallProgramSpecs struct {
	TracepointSchedSchedProcessExit    *ebpf.ProgramSpec `ebpf:"tracepoint__sched__sched_process_exit"`
	TracepointSyscallsSysEnterExecve   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_execve"`
	TracepointSyscallsSysEnterOpen     *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_open"`
	TracepointSyscallsSysEnterOpenat   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_openat"`
	TracepointSyscallsSysEnterOpenat2  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_openat2"`
	TracepointSyscallsSysExitExecve    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_execve"`
	TracepointSyscallsSysExitOpen      *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_open"`
	TracepointSyscallsSysExitOpenat    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_openat"`
	TracepointSyscallsSysExitOpenat2   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_openat2"`
	TracepointBtfSchedSchedProcessFork *ebpf.ProgramSpec `ebpf:"tracepoint_btf__sched__sched_process_fork"`
}

// bpf_smallMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_smallMapSpecs struct {
	DetectorConfig        *ebpf.MapSpec `ebpf:"detector_config"`
	EnvPrefix             *ebpf.MapSpec `ebpf:"env_prefix"`
	Events                *ebpf.MapSpec `ebpf:"events"`
	ExecFilesToFilter     *ebpf.MapSpec `ebpf:"exec_files_to_filter"`
	FileOpensByPid        *ebpf.MapSpec `ebpf:"file_opens_by_pid"`
	FilesOpenToTrack      *ebpf.MapSpec `ebpf:"files_open_to_track"`
	TrackedPidsToNsPids   *ebpf.MapSpec `ebpf:"tracked_pids_to_ns_pids"`
	UserPidToContainerPid *ebpf.MapSpec `ebpf:"user_pid_to_container_pid"`
}

// bpf_smallVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_smallVariableSpecs struct {
}

// bpf_smallObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpf_smallObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_smallObjects struct {
	bpf_smallPrograms
	bpf_smallMaps
	bpf_smallVariables
}

func (o *bpf_smallObjects) Close() error {
	return _Bpf_smallClose(
		&o.bpf_smallPrograms,
		&o.bpf_smallMaps,
	)
}

// bpf_smallMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpf_smallObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_smallMaps struct {
	DetectorConfig        *ebpf.Map `ebpf:"detector_config"`
	EnvPrefix             *ebpf.Map `ebpf:"env_prefix"`
	Events                *ebpf.Map `ebpf:"events"`
	ExecFilesToFilter     *ebpf.Map `ebpf:"exec_files_to_filter"`
	FileOpensByPid        *ebpf.Map `ebpf:"file_opens_by_pid"`
	FilesOpenToTrack      *ebpf.Map `ebpf:"files_open_to_track"`
	TrackedPidsToNsPids   *ebpf.Map `ebpf:"tracked_pids_to_ns_pids"`
	UserPidToContainerPid *ebpf.Map `ebpf:"user_pid_to_container_pid"`
}

func (m *bpf_smallMaps) Close() error {
	return _Bpf_smallClose(
		m.DetectorConfig,
		m.EnvPrefix,
		m.Events,
		m.ExecFilesToFilter,
		m.FileOpensByPid,
		m.FilesOpenToTrack,
		m.TrackedPidsToNsPids,
		m.UserPidToContainerPid,
	)
}

// bpf_smallVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpf_smallObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_smallVariables struct {
}

// bpf_smallPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpf_smallObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_smallPrograms struct {
	TracepointSchedSchedProcessExit    *ebpf.Program `ebpf:"tracepoint__sched__sched_process_exit"`
	TracepointSyscallsSysEnterExecve   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_execve"`
	TracepointSyscallsSysEnterOpen     *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_open"`
	TracepointSyscallsSysEnterOpenat   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_openat"`
	TracepointSyscallsSysEnterOpenat2  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_openat2"`
	TracepointSyscallsSysExitExecve    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_execve"`
	TracepointSyscallsSysExitOpen      *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_open"`
	TracepointSyscallsSysExitOpenat    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_openat"`
	TracepointSyscallsSysExitOpenat2   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_openat2"`
	TracepointBtfSchedSchedProcessFork *ebpf.Program `ebpf:"tracepoint_btf__sched__sched_process_fork"`
}

func (p *bpf_smallPrograms) Close() error {
	return _Bpf_smallClose(
		p.TracepointSchedSchedProcessExit,
		p.TracepointSyscallsSysEnterExecve,
		p.TracepointSyscallsSysEnterOpen,
		p.TracepointSyscallsSysEnterOpenat,
		p.TracepointSyscallsSysEnterOpenat2,
		p.TracepointSyscallsSysExitExecve,
		p.TracepointSyscallsSysExitOpen,
		p.TracepointSyscallsSysExitOpenat,
		p.TracepointSyscallsSysExitOpenat2,
		p.TracepointBtfSchedSchedProcessFork,
	)
}

func _Bpf_smallClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_small_x86_bpfel.o
var _Bpf_smallBytes []byte
