// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package probe

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpf_small_no_btfDetectorConfigT struct {
	_                    structs.HostLayout
	ConfiguredPidNsInode uint32
	Padding              [4]uint8
	NumOpenPathsToTrack  uint8
	NumExecPathsToFilter uint8
	Padding2             [6]uint8
}

type bpf_small_no_btfEnvPrefixT struct {
	_      structs.HostLayout
	Len    uint64
	Prefix [16]uint8
}

type bpf_small_no_btfExecFilenameT struct {
	_   structs.HostLayout
	Len uint64
	Buf [64]uint8
}

type bpf_small_no_btfOpenFilenameT struct {
	_   structs.HostLayout
	Len uint64
	Buf [128]uint8
}

// loadBpf_small_no_btf returns the embedded CollectionSpec for bpf_small_no_btf.
func loadBpf_small_no_btf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Bpf_small_no_btfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf_small_no_btf: %w", err)
	}

	return spec, err
}

// loadBpf_small_no_btfObjects loads bpf_small_no_btf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpf_small_no_btfObjects
//	*bpf_small_no_btfPrograms
//	*bpf_small_no_btfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpf_small_no_btfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf_small_no_btf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpf_small_no_btfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_small_no_btfSpecs struct {
	bpf_small_no_btfProgramSpecs
	bpf_small_no_btfMapSpecs
	bpf_small_no_btfVariableSpecs
}

// bpf_small_no_btfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_small_no_btfProgramSpecs struct {
	TracepointSchedSchedProcessExit   *ebpf.ProgramSpec `ebpf:"tracepoint__sched__sched_process_exit"`
	TracepointSchedSchedProcessFork   *ebpf.ProgramSpec `ebpf:"tracepoint__sched__sched_process_fork"`
	TracepointSyscallsSysEnterExecve  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_execve"`
	TracepointSyscallsSysEnterOpen    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_open"`
	TracepointSyscallsSysEnterOpenat  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_openat"`
	TracepointSyscallsSysEnterOpenat2 *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_openat2"`
	TracepointSyscallsSysExitExecve   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_execve"`
	TracepointSyscallsSysExitOpen     *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_open"`
	TracepointSyscallsSysExitOpenat   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_openat"`
	TracepointSyscallsSysExitOpenat2  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_openat2"`
}

// bpf_small_no_btfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_small_no_btfMapSpecs struct {
	DetectorConfig        *ebpf.MapSpec `ebpf:"detector_config"`
	EnvPrefix             *ebpf.MapSpec `ebpf:"env_prefix"`
	Events                *ebpf.MapSpec `ebpf:"events"`
	ExecFilesToFilter     *ebpf.MapSpec `ebpf:"exec_files_to_filter"`
	FileOpensByPid        *ebpf.MapSpec `ebpf:"file_opens_by_pid"`
	FilesOpenToTrack      *ebpf.MapSpec `ebpf:"files_open_to_track"`
	TrackedPidsToNsPids   *ebpf.MapSpec `ebpf:"tracked_pids_to_ns_pids"`
	UserPidToContainerPid *ebpf.MapSpec `ebpf:"user_pid_to_container_pid"`
}

// bpf_small_no_btfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpf_small_no_btfVariableSpecs struct {
}

// bpf_small_no_btfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpf_small_no_btfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_small_no_btfObjects struct {
	bpf_small_no_btfPrograms
	bpf_small_no_btfMaps
	bpf_small_no_btfVariables
}

func (o *bpf_small_no_btfObjects) Close() error {
	return _Bpf_small_no_btfClose(
		&o.bpf_small_no_btfPrograms,
		&o.bpf_small_no_btfMaps,
	)
}

// bpf_small_no_btfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpf_small_no_btfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_small_no_btfMaps struct {
	DetectorConfig        *ebpf.Map `ebpf:"detector_config"`
	EnvPrefix             *ebpf.Map `ebpf:"env_prefix"`
	Events                *ebpf.Map `ebpf:"events"`
	ExecFilesToFilter     *ebpf.Map `ebpf:"exec_files_to_filter"`
	FileOpensByPid        *ebpf.Map `ebpf:"file_opens_by_pid"`
	FilesOpenToTrack      *ebpf.Map `ebpf:"files_open_to_track"`
	TrackedPidsToNsPids   *ebpf.Map `ebpf:"tracked_pids_to_ns_pids"`
	UserPidToContainerPid *ebpf.Map `ebpf:"user_pid_to_container_pid"`
}

func (m *bpf_small_no_btfMaps) Close() error {
	return _Bpf_small_no_btfClose(
		m.DetectorConfig,
		m.EnvPrefix,
		m.Events,
		m.ExecFilesToFilter,
		m.FileOpensByPid,
		m.FilesOpenToTrack,
		m.TrackedPidsToNsPids,
		m.UserPidToContainerPid,
	)
}

// bpf_small_no_btfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpf_small_no_btfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_small_no_btfVariables struct {
}

// bpf_small_no_btfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpf_small_no_btfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpf_small_no_btfPrograms struct {
	TracepointSchedSchedProcessExit   *ebpf.Program `ebpf:"tracepoint__sched__sched_process_exit"`
	TracepointSchedSchedProcessFork   *ebpf.Program `ebpf:"tracepoint__sched__sched_process_fork"`
	TracepointSyscallsSysEnterExecve  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_execve"`
	TracepointSyscallsSysEnterOpen    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_open"`
	TracepointSyscallsSysEnterOpenat  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_openat"`
	TracepointSyscallsSysEnterOpenat2 *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_openat2"`
	TracepointSyscallsSysExitExecve   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_execve"`
	TracepointSyscallsSysExitOpen     *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_open"`
	TracepointSyscallsSysExitOpenat   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_openat"`
	TracepointSyscallsSysExitOpenat2  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_openat2"`
}

func (p *bpf_small_no_btfPrograms) Close() error {
	return _Bpf_small_no_btfClose(
		p.TracepointSchedSchedProcessExit,
		p.TracepointSchedSchedProcessFork,
		p.TracepointSyscallsSysEnterExecve,
		p.TracepointSyscallsSysEnterOpen,
		p.TracepointSyscallsSysEnterOpenat,
		p.TracepointSyscallsSysEnterOpenat2,
		p.TracepointSyscallsSysExitExecve,
		p.TracepointSyscallsSysExitOpen,
		p.TracepointSyscallsSysExitOpenat,
		p.TracepointSyscallsSysExitOpenat2,
	)
}

func _Bpf_small_no_btfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_small_no_btf_arm64_bpfel.o
var _Bpf_small_no_btfBytes []byte
